### ISSUE TITLE
onCreate issue

### ISSUE THREAD

**Issue by ray73864** [keejelo/EasyDialogBox#9]
For some reason I can't seem to override the onCreate function.

```
let myBox = EasyDialogBox.create("myBox", "dlg", "My Dialog Box", "<strong>This is my dialog box!</strong>");

myBox.onCreate = function() { alert("Created!"); };
myBox.onShow = function() { alert("Shown!"); };
myBox.onHide = function() { alert("Hidden!"); };
myBox.onDestroy = function() { alert("Destroyed!"); };

myBox.show();
```

onShow, onHide, and onDestroy all work perfectly.

If I set a breakpoint the ```mybox.show()``` and take a look at what myBox is made up of, I can see that it has my onCreate function defined, but if I set a breakpoint inside the onCreate function, it never gets triggered.

Looking at the code, it seems that it calls 'onCreate' during the creation function, which you would expect, and obviously calls it at that time, but obviously because I set the function later on, mine doesn't exist at that point.

And I can't move the onCreate to before the creation because then it errors out.

I can do what I want in the onShow anyway, which is to set a max-height for the dlg-message and set the overflow-y to scroll, so it isn't really an issue, but at this point in time, the onCreate event serves little purpose.

**Comment by keejelo** [comment]
Hi, I'll look into it later today when I get off work, see if I can fix it.
( I understand, the onCreate cannot be run if it don't exist yet, and it cannot be created before the object exist .. I see the mistake :) )

**Comment by keejelo** [comment]
I have a solution for this issue:
I added a fix to the "create" function so that the custom "onCreate" func runs async after the "create" has finished.

For the example you gave above this means it will now fire the "onShow" before "onCreate" due to its async.
So for those situations it might be more practical and best to do your stuff in the "onShow" func., (although it might not be an issue if one do not need to step through code with breakpoints like "alerts" or other ordered code sequences.)

But at least now the custom "onCreate" will execute if one needs to use it.
Can be situations when one need to create a dialog, but do not show it right away, and still need to trigger some "onCreate" stuff.
I will try to see if there's a better way of doing this, or if it has to be the "async" way (think it has to be async).

You can try the latest version (1.735.43 or later) of the file in the repos. and see if it works for you.  :)
https://github.com/keejelo/EasyDialogBox/blob/master/js/easydlg.js

**Comment by keejelo** [comment]
Just a quick thought about "async" (using version 1.735.43 or later):
One way to make your example code fire in correct sequence is to put the "obj.show()" at the end of the "obj.onCreate" function, if you need to create a dialog and show it immediately:
<pre>myBox.onCreate = function()
{ 
    alert("Created!");
    myBox.show();
};
</pre>
